kind: pipeline
name: default

steps:
  - name: build
    image: gradle:jdk8
    commands:
      - ./gradlew clean build
  - name: test
    image: gradle:jdk8
    commands:
      - ./gradlew test
  - name: docker
    image: plugins/docker
    tags: 1.1
    settings:
      repo: http://ec2-34-226-150-129.compute-1.amazonaws.com/mfinger
      registry: http://ec2-34-226-150-129.compute-1.amazonaws.com
  - name: publish
    image: plugins/ecr
    environment:
      repo: sfotex/mcapp
    settings:
      access_key:
        from_secret: access_key
      secret_key:
        from_secret: secret_key

      repo: drone
      registry: 246488978151.dkr.ecr.us-east-1.amazonaws.com

