kind: pipeline
name: default

steps:
  - name: build
    image: gradle:jdk8
    commands:
      - ./gradlew clean build
  - name: test
    image: gradle:jdk8
    commands:
      - ./gradlew test
  - name: docker
    image: plugins/docker
    settings:
      tags: latest
      repo: mfinger/drone
      username: mfinger
      password:
        from_secret: docker_pw
  - name: publish
    image: plugins/ecr
    settings:
      access_key:
        from_secret: access_key
      secret_key:
        from_secret: secret_key
      repo: drone
      registry: 246488978151.dkr.ecr.us-east-1.amazonaws.com
      tags:
         ${DRONE_COMMIT_SHA:0:8}

