resources:
  - name: spring-boot-concourse
    type: git
    check_every: 10s
    source:
      uri: https://github.com/sfotex/mcapp.git
      branch: master   
  - name: my-docker-image
    type: docker-image
    source:
      repository: host.docker.internal:5000/my-spring
      insecure_registries: ["http://host.docker.internal:5000"]

jobs:
- name: build
  public: true
  plan:
  - get: spring-boot-concourse
    trigger: true
  - task: Build project
    file: spring-boot-concourse/concourse/tasks/build.yml
  - task: Deploy artifact
    file: spring-boot-concourse/concourse/tasks/deploy.yml
  - put: my-docker-image
    params:
      build: ./spring-boot-concourse/
