platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: spring-boot-concourse

outputs:
  - name: build-output

run:
  path: "spring-boot-concourse/concourse/tasks/build.sh"