---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: http://fingerm19:5000/v2/spring-boot-concourse

inputs:
  - name: build-output

run:
  path: ls
  args: ["build-output"]
