---
platform: linux


image_resource:
  type: docker-image
  source:
    repository: tomkukral/buildah
    tag: "latest"

    
inputs:
  - name: build-output

run:
  path: sh
  args: [buildah bud -t build-output/Dockerbuild .]