---
platform: linux


image_resource:
  type: docker-image
  source: {tag: tomkukral/buildah}
    
inputs:
  - name: build-output

run:
  path: sh
  args: [spring-boot-concourse/concourse/tasks/deploy.sh]