---
platform: linux

- name: hello-world-docker-image
  type: docker-image
  source:
    repository: host.docker.internal:5000/my-spring
    insecure_registries: ["http://host.docker.internal:5000"]

inputs:
  - name: build-output

outputs:
  - name: hello-world-docker-image

run:
  path: ls
  args: ["build-output"]
