---
platform: linux


image_resource:
  type: docker-image
  source: {repository: java, tag: tomkukral/buildah}
    
inputs:
  - name: build-output

caches:
  - path: gradle
  - path: maven

run:
  path: ls
  args: ["build-output"]