---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: host.docker.internal:5000/my-spring
    insecure_registries: ["http://host.docker.internal:5000"]

inputs:
  - name: build-output

run:
  path: ls
  args: ["build-output"]
