---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: build-output

run:
  path: "spring-boot-concourse"
  args:
  - -c
  - gradlew build docker