---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: http://fingerm19:5000/spring-boot-concourse
    insecure_registries: ["http://fingerm19:5000"]

inputs:
  - name: build-output

run:
  path: ls
  args: ["build-output"]
