---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8-alpine}

inputs:
  - name: spring-boot-concourse

caches:
  - path: gradle
  - path: maven

run:
  path: "spring-boot-concourse/concourse/tasks/deploy.sh"