---
platform: linux


image_resource:
  type: docker-image
  source:
    repository: marshallford/podman
    tag: "latest"

    
inputs:
  - name: build-output
  - name: spring-boot-concourse

run:
  path: sh
  args: [spring-boot-concourse/concourse/tasks/deploy.sh]